version: "3.9"

networks:
  rabbitmq: {}

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 500M
        reservations:
          cpus: '1.00'
          memory: 200M
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
    networks:
      - rabbitmq

  rabbitmq-reader:
    image: sh1co/rabbitmq-reader:1.1.0
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - rabbitmq
    depends_on:
      - rabbitmq
